api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "payment-bypass"
type = "function"
uid = "00ab54fb-32d7-d2a9-742b-974751b47316e6ec6ec1"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
