# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4743f232818b9ba5b2a8cb8ced19bcdf"
name = "Discount Threshold Manager"
application_url = "https://discount-threshold-manager.up.railway.app/"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "customers/data_request" ]
uri = "/webhooks/customers-data-request"

[[webhooks.subscriptions]]
topics = [ "customers/redact" ]
uri = "/webhooks/customers-redact"

[[webhooks.subscriptions]]
topics = [ "shop/redact" ]
uri = "/webhooks/shop-redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,write_discounts"

[auth]
redirect_urls = [
  "https://discount-threshold-manager.up.railway.app/api/auth"
]
