# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4743f232818b9ba5b2a8cb8ced19bcdf"
name = "ThresholdFlow"
application_url = "https://discount-threshold-manager.up.railway.app/"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop-redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,read_payment_customizations,read_products,write_discounts,write_orders,write_payment_customizations,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://discount-threshold-manager.up.railway.app/" ]
