# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b2f695311778c104ba4968dc6efcc827"
name = "app 2.0"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
