import React from "react";
import { BlockStack, InlineGrid } from "@shopify/polaris";
import AnalyticsCard from "./AnalyticsCard";
import Forecasting from "./Forecasting";

function Overview({
  activeDateRange,
  setPopoverActive,
  forecastingDateRange,
  setForecastingDateRange,
  forecastingPopoverActive,
  setForecastingPopoverActive,
  forecastingInputValues,
  setForecastingInputValues,
  forecastingMonth,
  setForecastingMonth,
  searchValue,
  setSearchValue,
  suggestions,
  setSuggestions,
  loading,
  setLoading,
  showSuggestions,
  setShowSuggestions,
  filteredData,
  ranges,
  mdDown,
  lgUp,
}: {
  activeDateRange: any;
  setPopoverActive: (active: boolean) => void;
  forecastingDateRange: any;
  setForecastingDateRange: (range: any) => void;
  forecastingPopoverActive: boolean;
  setForecastingPopoverActive: (active: boolean) => void;
  forecastingInputValues: { since?: string; until?: string };
  setForecastingInputValues: React.Dispatch<
    React.SetStateAction<{ since?: string; until?: string }>
  >;
  forecastingMonth: { month: number; year: number };
  setForecastingMonth: React.Dispatch<
    React.SetStateAction<{ month: number; year: number }>
  >;
  searchValue: string;
  setSearchValue: (value: string) => void;
  suggestions: string[];
  setSuggestions: (suggestions: string[]) => void;
  loading: boolean;
  setLoading: (loading: boolean) => void;
  showSuggestions: boolean;
  setShowSuggestions: (show: boolean) => void;
  filteredData: any[];
  ranges: any[];
  mdDown: boolean;
  lgUp: boolean;
}) {
  const tooltip1 = (
    <div>
      <p>
        <strong>Total Orders</strong> represent the cumulative count of both{" "}
        <strong>initial orders</strong> and <strong>recurring orders</strong>{" "}
        processed within the specified date range.
      </p>
      <p>
        <strong>Initial Orders</strong> refer to the inaugural transaction upon
        the initiation of a subscription contract.
      </p>
      <p>
        <strong>Recurring Orders</strong> encompass subsequent transactions made
        within a subscription following the initial order.
      </p>
    </div>
  );

  const tooltip2 =
    "The total number of new subscription contracts that were created within the selected date range, irrespective of their current status (active, canceled, or paused).";

  const tooltip3 =
    "The average total revenue generated by individual subscription contracts that were created within the selected date range. This sum includes all revenue (initial and recurring) generated by these specific contracts up to the current date, regardless of their current status (active, canceled, or paused).";

  const tooltip4 =
    "The average number of days a subscription remains active, calculated from its creation date up to the end date of the selected period. This average includes only subscriptions that were active at the end of the selected period and were created on or before that date.";

  const tooltip5 =
    "The net change in your total active subscriptions over the selected date range. This is calculated by taking the total active subscriptions on the last day of the selected period and subtracting the total active subscriptions from the day immediately preceding the selected period's start date.";

  const tooltip6 =
    "The average number of successful recurring orders processed per subscription. This is calculated by dividing the total number of successful recurring orders by the count of unique subscription contracts that generated those orders, measured up to the end date of the selected period.";

  return (
    <>
      <BlockStack gap={"400"}>
        <InlineGrid columns={{ xs: 1, md: 2 }} gap="400">
          {/* Total orders */}
          <AnalyticsCard
            title="Total Orders"
            leftButton="date"
            value="0"
            tooltipContent={tooltip1}
            activeDateRange={activeDateRange}
            setPopoverActive={setPopoverActive}
          />
          {/* Total Subscription Created */}
          <AnalyticsCard
            title="Total Subscriptions Created"
            leftButton="date"
            value="0"
            tooltipContent={tooltip2}
            activeDateRange={activeDateRange}
            setPopoverActive={setPopoverActive}
          />
          {/* Average Lifetime Revenue */}
          <AnalyticsCard
            title="Average Lifetime Revenue"
            leftButton={null}
            value="RS. 0.00"
            tooltipContent={tooltip3}
            activeDateRange={activeDateRange}
            setPopoverActive={setPopoverActive}
          />
          {/* Average Subscriptions Lifetime */}
          <AnalyticsCard
            title="Average Subscription Lifetime"
            leftButton={null}
            value="0 Days"
            tooltipContent={tooltip4}
            activeDateRange={activeDateRange}
            setPopoverActive={setPopoverActive}
          />
          {/* Net Gained/Loss Subscriptions */}
          <AnalyticsCard
            title="Net Gained/Loss Subscriptions"
            leftButton="date"
            value="0"
            tooltipContent={tooltip5}
            activeDateRange={activeDateRange}
            setPopoverActive={setPopoverActive}
          />
          {/* Average Orders Per Subscriptions */}
          <AnalyticsCard
            title="Average Orders Per Subscription"
            leftButton={null}
            value="0"
            tooltipContent={tooltip6}
            activeDateRange={activeDateRange}
            setPopoverActive={setPopoverActive}
          />
        </InlineGrid>
        <Forecasting
          forecastingDateRange={forecastingDateRange}
          setForecastingDateRange={setForecastingDateRange}
          forecastingPopoverActive={forecastingPopoverActive}
          setForecastingPopoverActive={setForecastingPopoverActive}
          forecastingInputValues={forecastingInputValues}
          setForecastingInputValues={setForecastingInputValues}
          forecastingMonth={forecastingMonth}
          setForecastingMonth={setForecastingMonth}
          searchValue={searchValue}
          setSearchValue={setSearchValue}
          suggestions={suggestions}
          setSuggestions={setSuggestions}
          loading={loading}
          setLoading={setLoading}
          showSuggestions={showSuggestions}
          setShowSuggestions={setShowSuggestions}
          filteredData={filteredData}
          ranges={ranges}
          mdDown={mdDown}
          lgUp={lgUp}
        />
      </BlockStack>
    </>
  );
}

export default Overview;