export interface ConfigurationField {
  key: string;
  fieldType: 'checkbox' | 'text input' | 'options - dropdown' | 'number input' | 'multi-select';
  fieldLabel: string;
  fieldTooltipContent?: string;
  fieldValue: string | boolean;
  fieldPlaceholder?: string;
  fieldDescription?: string;
  disable?: boolean;
  fieldOptions?: string;
  suffix?: string;
}

export interface ConfigurationSection {
  title: string;
  description?: string;
  fields: ConfigurationField[];
}

export const configurationSections: ConfigurationSection[] = [
  {
    title: "Subscription Management",
    fields: [
      {
        key: "allowCustomersToCancelSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Allow customers to cancel subscriptions",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Enable a cancel button that lets customers end their subscriptions completely.",
        fieldValue: true,
      },
      {
        key: "allowCustomersToPauseSubscriptionsTemporarily",
        fieldType: "checkbox",
        fieldLabel: "Allow customers to pause subscriptions temporarily",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Enable a pause button that lets customers temporarily stop their subscriptions and resume them later.",
        fieldValue: true,
      },
      {
        key: "allowCustomersToResumePausedOrCanceledSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Allow customers to resume paused or canceled subscriptions",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Enable a resume button that lets customers restart their subscriptions after pausing or canceling.",
        fieldValue: true,
      },
      {
        key: "allowCustomersToProcessTheirNextSubscriptionOrderImmediately",
        fieldType: "checkbox",
        fieldLabel: "Allow customers to process their next subscription order immediately",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Enables an 'Order Now' button that lets customers receive their next scheduled order right away.",
        fieldValue: true,
      },
      {
        key: "allowCustomersToSkipTheirUpcomingSubscriptionOrder",
        fieldType: "checkbox",
        fieldLabel: "Allow customers to skip their upcoming subscription order",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Enables a 'Skip' button that lets customers skip their next scheduled delivery without canceling the subscription.",
        fieldValue: true,
      },
    ],
  },
  {
    title: "Order Customization",
    fields: [
      {
        key: "letCustomersRemoveProductsFromTheirSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Let customers remove products from their subscriptions",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Allows customers to delete unwanted products from their subscriptions. Note: For product bundles, customers can only swap products rather than remove them.",
        fieldValue: true,
      },
      {
        key: "letCustomersAddNotesToTheirOrders",
        fieldType: "checkbox",
        fieldLabel: "Let customers add notes to their orders",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Allows customers to include special instructions (like delivery preferences) with their upcoming orders. You'll see these notes in your merchant dashboard.",
        fieldValue: false,
      },
      {
        key: "letCustomersSkipIndividualFulfillmentOrdersFromTheFulfillmentTab",
        fieldType: "checkbox",
        fieldLabel: "Let customers skip individual fulfillment orders from the fulfillment tab.",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "This setting is used to hide the skip button for Prepaid Contracts in the fulfillment tab and not for All Contracts.",
        fieldValue: false,
      },
      {
        key: "letCustomersChangeHowOftenTheyReceiveOrders",
        fieldType: "checkbox",
        fieldLabel: "Let customers change how often they receive orders",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Allows customers to adjust their delivery frequency (e.g., from monthly to biweekly).",
        fieldValue: true,
      },
      {
        key: "showOnlyFrequenciesAvailableInCurrentSubscriptionGroup",
        fieldType: "checkbox",
        fieldLabel: "Show only frequencies available in current subscription group",
        fieldPlaceholder: "none",
        fieldDescription: "When enabled, customers will only see the delivery frequencies available in the subscription group of their current contract.",
        fieldTooltipContent: "none",
        fieldValue: false,
      },
      {
        key: "limitDeliveryFrequencyOptions",
        fieldType: "options - dropdown",
        fieldLabel: "Limit delivery frequency options",
        fieldPlaceholder: "none",
        fieldDescription: "When enabled, customers can only choose from the delivery frequencies you have set up in your subscription plans. This setting only works when \"Let customers change how often they receive orders\" is enabled above.",
        fieldTooltipContent: "none",
        fieldOptions: "Enable , Disable",
        fieldValue: "Enable",
      },
    ],
  },
  {
    title: "Account Access And Security",
    fields: [
      {
        key: "letCustomersReturnToTheirAccountPageWhenClickingMyAccount",
        fieldType: "checkbox",
        fieldLabel: "Let customers return to their account page when clicking 'My Account'",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "Adds a back button that helps customers navigate back to their account page while managing subscriptions.",
        fieldValue: true,
      },
      {
        key: "customDestinationWhenCustomersClickMyAccount",
        fieldType: "text input",
        fieldLabel: "Custom destination when customers click 'My Account' (optional)",
        fieldPlaceholder: "none",
        fieldDescription: "This field is disabled because 'Let customers return to their account page when clicking My Account' option is enabled.",
        fieldTooltipContent: "By default, the 'My Account' button takes customers to their account page. You can enter a different destination URL here if needed.",
        fieldValue: "",
        disable: true,
      },
      {
        key: "letCustomersViewFullProductDetailsByClickingOnProductImagesOrTitles",
        fieldType: "checkbox",
        fieldLabel: "Let customers view full product details by clicking on product images or titles",
        fieldPlaceholder: "none",
        fieldDescription: "none",
        fieldTooltipContent: "When enabled, customers can click product images or names to see the full product page in your store.",
        fieldValue: false,
      },
    ],
  },
  {
    title: "Discounts And Promotions",
    fields: [
      {
        key: "letCustomersApplyDiscountCodesToTheirSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Let customers apply discount codes to their subscriptions",
        fieldTooltipContent: "Allows customers to use promotional codes on their subscription orders.",
        fieldValue: true,
      },
      {
        key: "limitCustomersToUsingOnlyOneDiscountCodePerSubscription",
        fieldType: "checkbox",
        fieldLabel: "Limit customers to using only one discount code per subscription",
        fieldTooltipContent: "When enabled, customers can only apply one discount code. When disabled, they can use multiple discount codes together.",
        fieldValue: false,
      },
      {
        key: "displayProductCustomizationsToCustomers",
        fieldType: "checkbox",
        fieldLabel: "Display product customizations to customers",
        fieldTooltipContent: "Shows customers their selected product options and customizations in the subscription portal.",
        fieldValue: false,
      },
      {
        key: "letCustomersChangeProductQuantities",
        fieldType: "checkbox",
        fieldLabel: "Let customers change product quantities",
        fieldTooltipContent: "Allows customers to increase or decrease how many of each product they receive in their subscription.",
        fieldValue: true,
      },
      {
        key: "letCustomersEditTheirOrderNotes",
        fieldType: "checkbox",
        fieldLabel: "Let customers edit their order notes",
        fieldTooltipContent: "Allows customers to update delivery instructions or other notes for their upcoming orders.",
        fieldValue: true,
      },
    ],
  },
  {
    title: "Product And Shipping Management",
    fields: [
      {
        key: "letCustomersUpdateTheirShippingAddress",
        fieldType: "checkbox",
        fieldLabel: "Let customers update their shipping address",
        fieldTooltipContent: "Allows customers to change where their subscription orders are delivered.",
        fieldValue: true,
      },
      {
        key: "letCustomersAddMoreProductsToTheirExistingSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Let customers add more products to their existing subscriptions",
        fieldTooltipContent: "Enables an 'Add Products' feature so customers can include additional items in their subscription.",
        fieldValue: true,
      },
      {
        key: "letCustomersAddItemsToTheirProductBundleSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Let customers add items to their product bundle subscriptions",
        fieldTooltipContent: "Enables customers to add new products to their Build A Box or product bundle subscriptions.",
        fieldValue: false,
      },
      {
        key: "letCustomersSkipSpecificProductsInTheirNextOrder",
        fieldType: "checkbox",
        fieldLabel: "Let customers skip specific products in their next order",
        fieldTooltipContent: "Allows customers to receive most of their subscription but skip individual products for just their next delivery.",
        fieldValue: false,
      },
      {
        key: "customizeDeliveryScheduleOptionsBasedOnCustomerTags",
        fieldType: "checkbox",
        fieldLabel: "Customize delivery schedule options based on customer tags",
        fieldTooltipContent: "Use customer tags to offer different delivery schedules to different customer groups.",
        fieldValue: false,
      },
    ],
  },
  {
    title: "Next Order Management",
    fields: [
      {
        key: "letCustomersRescheduleTheirNextUpcomingDelivery",
        fieldType: "checkbox",
        fieldLabel: "Let customers reschedule their next upcoming delivery",
        fieldTooltipContent: "Allows customers to change the date of their next subscription order.",
        fieldValue: true,
      },
      {
        key: "letCustomersAdjustTheScheduleForFutureDeliveries",
        fieldType: "checkbox",
        fieldLabel: "Let customers adjust the schedule for future deliveries",
        fieldTooltipContent: "Allows customers to reschedule orders beyond their next upcoming delivery.",
        fieldValue: false,
      },
    ],
  },
  {
    title: "Product Configuration",
    fields: [
      {
        key: "letCustomersExchangeProductsInTheirSubscription",
        fieldType: "checkbox",
        fieldLabel: "Let customers exchange products in their subscription",
        fieldTooltipContent: "Enables a 'Swap' option so customers can replace products in their subscription with different ones. For product bundles, this allows swapping between items in the same bundle.",
        fieldValue: true,
      },
      {
        key: "letCustomersSubscribeToOutOfStockProducts",
        fieldType: "checkbox",
        fieldLabel: "Let customers subscribe to out-of-stock products",
        fieldTooltipContent: "When enabled, customers can add products that are currently out of stock to their subscriptions. They'll start receiving these products once they're back in stock.",
        fieldValue: true,
      },
      {
        key: "letCustomersChangeQuantitiesEvenWhenProductsAreOutOfStock",
        fieldType: "checkbox",
        fieldLabel: "Let customers change quantities even when products are out of stock",
        fieldTooltipContent: "Allows customers to increase or decrease the quantity of products in their subscription even if those products are currently unavailable.",
        fieldValue: false,
      },
      {
        key: "letCustomersAdjustQuantitiesInTheirProductBundles",
        fieldType: "checkbox",
        fieldLabel: "Let customers adjust quantities in their product bundles",
        fieldTooltipContent: "Allows customers to change the quantities of products within their Build A Box or bundle subscriptions.",
        fieldValue: false,
      },
    ],
  },
  {
    title: "Contract Management",
    fields: [
      {
        key: "automaticallyRemoveProductSpecificDiscountsWhenThatProductIsRemoved",
        fieldType: "checkbox",
        fieldLabel: "Automatically remove product-specific discounts when that product is removed",
        fieldTooltipContent: "When a customer removes a product from their subscription, any discount tied specifically to that product will also be removed.",
        fieldValue: false,
      },
      {
        key: "removeQuantityLimitsForProductBundleSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Remove quantity limits for product bundle subscriptions",
        fieldTooltipContent: "Ignores any minimum or maximum quantity restrictions for products in Build A Box subscriptions.",
        fieldValue: false,
      },
      {
        key: "letCustomersRescheduleDeliveriesDuringTheirTrialPeriod",
        fieldType: "checkbox",
        fieldLabel: "Let customers reschedule deliveries during their trial period",
        fieldTooltipContent: "Allow customers to change delivery dates even when they're in a free or discounted trial period.",
        fieldValue: false,
      },
      {
        key: "letCustomersSwitchBetweenProductOptions",
        fieldType: "checkbox",
        fieldLabel: "Let customers switch between product options (e.g., size, color)",
        fieldTooltipContent: "Allows customers to change variants of products in their subscription without swapping for a completely different product.",
        fieldValue: false,
      },
      {
        key: "letCustomersReuseDiscountRetentionOffers",
        fieldType: "checkbox",
        fieldLabel: "Let customers reuse discount retention offers",
        fieldTooltipContent: "If enabled, customers can select the same retention discount again when trying to cancel. If they choose the same discount again, their subscription will be canceled automatically.",
        fieldValue: false,
      },
    ],
  },
  {
    title: "Currency Settings",
    fields: [
      {
        key: "enableSupportForMultipleCurrencies",
        fieldType: "checkbox",
        fieldLabel: "Enable support for multiple currencies",
        fieldTooltipContent: "This feature only works if your store already has Shopify's multi-currency feature enabled.",
        fieldValue: true,
      },
    ],
  },
  {
    title: "Subscription List Settings",
    fields: [
      {
        key: "skipTheSubscriptionListPageIfThereIsOnlyOneContract",
        fieldType: "checkbox",
        fieldLabel: "Skip the subscription list page if there is only one contract",
        fieldTooltipContent: "If this is ON and the customer has only one subscription, it will open that subscription directly instead of showing a list.",
        fieldValue: true,
      },
    ],
  },
  {
    title: "Minimum Order Settings",
    fields: [
      {
        key: "lockSubscriptionChangesUntilMinimumOrderCountIsReached",
        fieldType: "checkbox",
        fieldLabel: "Lock subscription changes until minimum order count is reached",
        fieldDescription: "Upgrade your plan to BUSINESS to enable this feature.",
        fieldTooltipContent: "Prevents customers from making any changes to their subscription until they've received the minimum required number of orders.",
        fieldValue: "false",
        disable: true,
      },
      {
        key: "allowProductSwapsBeforeMinimumOrderCountIsReached",
        fieldType: "checkbox",
        fieldLabel: "Allow product swaps before minimum order count is reached",
        fieldDescription: "Upgrade your plan to BUSINESS to enable this feature.",
        fieldTooltipContent: "Even when subscriptions are locked for changes, customers can still exchange one product for another.",
        fieldValue: "false",
        disable: true,
      },
    ],
  },
  {
    title: "One-time Product",
    fields: [
      {
        key: "letCustomersAddOneTimePurchasesToTheirSubscriptionOrders",
        fieldType: "checkbox",
        fieldLabel: "Let customers add one-time purchases to their subscription orders",
        fieldDescription: "Upgrade your plan to BUSINESS to enable this feature.",
        fieldTooltipContent: "Enables customers to add products they want to receive just once with their next subscription delivery.",
        fieldValue: "false",
        disable: true,
      },
      {
        key: "allowOneTimePurchasesWithPrepaidSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Allow one-time purchases with prepaid subscriptions",
        fieldDescription: "One-time products will be added to the next billing cycle. They will not be added to orders that have already been processed.\nUpgrade your plan to BUSINESS to enable this feature.",
        fieldTooltipContent: "Let customers add one-time products even when they've already paid upfront for multiple deliveries.",
        fieldValue: "false",
        disable: true,
      },
      {
        key: "letCustomersRemoveOneTimeProductsFromTheirNextOrder",
        fieldType: "checkbox",
        fieldLabel: "Let customers remove one-time products from their next order",
        fieldDescription: "Upgrade your plan to BUSINESS to enable this feature.",
        fieldTooltipContent: "Allows customers to cancel one-time products they've previously added to their upcoming delivery.",
        fieldValue: "false",
        disable: true,
      },
      {
        key: "excludeSubscriptionOnlyProductsFromOneTimePurchaseOptions",
        fieldType: "checkbox",
        fieldLabel: "Exclude subscription-only products from one-time purchase options",
        fieldTooltipContent: "When enabled, products that require a subscription cannot be added as one-time purchases.",
        fieldValue: "true",
        disable: false,
      },
    ],
  },
  {
    title: "Split & Merge Contract",
    fields: [
      {
        key: "allowCustomersToSplitOneSubscriptionIntoMultipleSubscriptions",
        fieldType: "checkbox",
        fieldLabel: "Allow customers to split one subscription into multiple subscriptions",
        fieldDescription: "Upgrade your plan to BUSINESS to enable this feature.",
        fieldTooltipContent: "Customers can separate products from a single subscription into separate individual subscriptions.",
        fieldValue: "false",
        disable: true,
      },
      {
        key: "allowCustomersToCombineMultipleSubscriptionsIntoOne",
        fieldType: "checkbox",
        fieldLabel: "Allow customers to combine multiple subscriptions into one",
        fieldDescription: "Upgrade your plan to BUSINESS to enable this feature.",
        fieldTooltipContent: "Customers can merge two or more of their subscriptions together into a single subscription.",
        fieldValue: "false",
        disable: true,
      },
    ],
  },
  {
    title: "Delivery Settings",
    fields: [
      {
        key: "letCustomersChangeShippingMethods",
        fieldType: "checkbox",
        fieldLabel: "Let customers change shipping methods",
        fieldTooltipContent: "When multiple shipping options are available, customers can switch between them (e.g., from standard to express delivery).",
        fieldValue: "true",
        disable: false,
      },
    ],
  },
  {
    title: "Date & Time Settings",
    fields: [
      {
        key: "calendarLanguageAndFormat",
        fieldType: "options - dropdown",
        fieldLabel: "Calendar language and format",
        fieldOptions: "English, French, German, Spanish, Italian, Portuguese, Dutch, Swedish, Norwegian, Danish, Finnish, Polish, Czech, Slovak, Hungarian, Romanian, Bulgarian, Croatian, Slovenian, Estonian, Latvian, Lithuanian, Greek, Turkish, Arabic, Hebrew, Chinese, Japanese, Korean",
        fieldValue: "English",
      },
      {
        key: "howDatesAppearToYourCustomers",
        fieldType: "text input",
        fieldLabel: "How dates appear to your customers",
        fieldDescription: "Please visit this link to learn more about date formats (e.g., \"MMM d, yyyy\" displays as \"May 17, 2023\").",
        fieldValue: "EEE, dd MMMM yyyy",
      },
      {
        key: "daysOfTheWeekCustomersCanScheduleDeliveries",
        fieldType: "multi-select",
        fieldLabel: "Days of the week customers can schedule deliveries",
        fieldValue: "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
        fieldOptions: "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
      },
      {
        key: "startingPointForDateSelection",
        fieldType: "options - dropdown",
        fieldLabel: "Starting point for date selection",
        fieldDescription: "Choose whether customers start selecting new dates from today or from their last order date.",
        fieldValue: "Today's date",
        fieldOptions: "Today's date, Last billing date",
      },
      {
        key: "howFarInAdvanceCustomersCanSchedule",
        fieldType: "number input",
        fieldLabel: "How far in advance customers can schedule (days)",
        fieldTooltipContent: "This limits how far in the future customers can reschedule. For example, with a 60-day limit and a next order date of Sept 1, customers could only reschedule up to Oct 30.",
        fieldValue: "",
      },
    ],
  },
  {
    title: "Customer Portal Display",
    fields: [
      {
        key: "promotionalMessageForAddingProducts",
        fieldType: "text input",
        fieldLabel: "Promotional message for adding products",
        fieldDescription: "A message encouraging customers to add more products to their subscription.",
        fieldValue: "Add another product at a discounted price!",
      },
      {
        key: "processingBufferDaysFromToday",
        fieldType: "number input",
        fieldLabel: "Processing buffer (days from today)",
        fieldDescription: "Processing buffer days should always be greater than 'How far in advance customers can schedule (days)' value. If both values are the same, rescheduling will not work.",
        fieldTooltipContent: "Customers won't be able to select dates within this many days from today when rescheduling.\nNote: A value of 3 means customers can only reschedule for dates at least 3 days from today.",
        fieldValue: "",
      },
    ],
  },
  {
    title: "Product Display & Filtering",
    fields: [
      {
        key: "allowProductRemovalInBundledSubscriptions",
        fieldType: "options - dropdown",
        fieldLabel: "Allow product removal in bundled subscriptions",
        fieldDescription: "Controls whether customers can remove products from Build A Box subscriptions.",
        fieldValue: "Disable",
        fieldOptions: "Disable, Enable",
      },
      {
        key: "productsToShowPerPage",
        fieldType: "options - dropdown",
        fieldLabel: "Products to show per page",
        fieldDescription: "Controls how many products appear on each page of the customer portal.",
        fieldValue: "20",
        fieldOptions: Array.from({ length: 100 }, (_, i) => (i + 1).toString()).join(", "),
      },
      {
        key: "minimumQuantityWhenAddingOrChangingProducts",
        fieldType: "number input",
        fieldLabel: "Minimum quantity when adding or changing products",
        fieldDescription: "The minimum number of units customers must add when modifying their subscription.",
        fieldValue: "1",
      },
    ],
  },
  {
    title: "Order & Subscription Management",
    fields: [
      {
        key: "overrideFixedDeliveryDayRestrictions",
        fieldType: "checkbox",
        fieldLabel: "Override fixed delivery day restrictions",
        fieldTooltipContent: "If customers have fixed delivery days (like every Monday), enabling this will allow them to reschedule to any day you've enabled above, not just Mondays.",
        fieldValue: "false",
      },
      {
        key: "showEstimatedDeliveryDateRange",
        fieldType: "checkbox",
        fieldLabel: "Show estimated delivery date range",
        fieldDescription: "Displays an estimated delivery window to customers in addition to the order processing date.",
        fieldValue: "false",
      },
      {
        key: "applySubscriptionDiscountsToOneTimePurchases",
        fieldType: "checkbox",
        fieldLabel: "Apply subscription discounts to one-time purchases",
        fieldTooltipContent: "When enabled, all subscription discounts will also apply to one-time products added to subscription orders.",
        fieldValue: "false",
      },
      {
        key: "discountPolicyForAddedProducts",
        fieldType: "options - dropdown",
        fieldLabel: "Discount policy for added products",
        fieldDescription: "When adding products to a subscription, we'll first check if the product has its own subscription discount. If not, we'll apply the current subscription's discount.",
        fieldValue: "Use best available discount",
        fieldOptions: "No discount on added products, Apply current subscription discount, Apply product's own subscription discount, Use best available discount",
      },
      {
        key: "offerAdditionalDiscountForAddingProductsToSubscription",
        fieldType: "checkbox",
        fieldLabel: "Offer additional discount for adding products to subscription",
        fieldDescription: "Encourages customers to add more products by offering a special discount.",
        fieldValue: "false",
      },
    ],
  },
  {
    title: "Subscription Timing Restrictions",
    fields: [
      {
        key: "blockCancellationPauseOrSkipActions",
        fieldType: "text input",
        fieldLabel: "Block cancellation, pause, or skip actions",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "within",
        disable: true,
        suffix: "days of next order date",
      },
      {
        key: "blockAddingEditingSwappingOrRemovingProducts",
        fieldType: "text input",
        fieldLabel: "Block adding, editing, swapping, or removing products",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "within",
        disable: true,
        suffix: "days of next order date",
      },
      {
        key: "allowedDaysToCancelPauseOrSkipOrders",
        fieldType: "text input",
        fieldLabel: "Allowed days to cancel, pause, or skip orders",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "up to",
        disable: true,
        suffix: "days before the next order date",
      },
      {
        key: "allowProductModificationsTiming",
        fieldType: "text input",
        fieldLabel: "Allow product modifications timing",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "up to",
        disable: true,
        suffix: "days before next order date",
      },
    ],
  },
  {
    title: "Subscription Product Restrictions",
    description: "Control which products can be added to subscriptions or one-time purchases",
    fields: [
      {
        key: "productsThatCannotBeEditedRemovedOrSwapped",
        fieldType: "text input",
        fieldLabel: "Products that cannot be edited, removed, or swapped (Variant IDs)",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "",
        disable: true,
      },
      {
        key: "productVariantsNotAvailableForOneTimePurchase",
        fieldType: "text input",
        fieldLabel: "Product variants not available for one-time purchase (Variant IDs)",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "",
        disable: true,
      },
      {
        key: "productsNotAvailableForOneTimePurchase",
        fieldType: "text input",
        fieldLabel: "Products not available for one-time purchase (Product IDs)",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "",
        disable: true,
      },
      {
        key: "productsAvailableForOneTimePurchase",
        fieldType: "text input",
        fieldLabel: "Products available for one-time purchase (Product IDs)",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "",
        disable: true,
      },
      {
        key: "productVariantsNotAvailableForSubscription",
        fieldType: "text input",
        fieldLabel: "Product variants not available for subscription (Variant IDs)",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "",
        disable: true,
      },
    ],
  },
  {
    title: "Allowed Subscription Products\nand Addresses",
    fields: [
      {
        key: "whichProductsCustomersCanAddToSubscriptions",
        fieldType: "options - dropdown",
        fieldLabel: "Which products customers can add to subscriptions",
        fieldDescription: "Controls the range of products customers can add to their existing subscriptions.",
        fieldValue: "Any product with a subscription option",
        fieldOptions: "Any product in your store, Any product with a subscription option, Only products from the customer's current subscription plan",
      },
      {
        key: "productsAndVariantsAvailableForSubscription",
        fieldType: "text input",
        fieldLabel: "Products and variants available for subscription (comma-separated IDs)",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldTooltipContent: "For variant-specific subscriptions, enter variant IDs. For product-level subscriptions, enter product IDs.",
        fieldValue: "",
        disable: true,
      },
      {
        key: "productTagsAllowedForSubscriptionPurchase",
        fieldType: "text input",
        fieldLabel: "Product tags allowed for subscription purchase",
        fieldDescription: "Products with these tags will be available for customers to add to their subscriptions.",
        fieldValue: "",
      },
      {
        key: "productTagsNotAllowedForSubscriptionPurchase",
        fieldType: "text input",
        fieldLabel: "Product tags not allowed for subscription purchase",
        fieldDescription: "Products with these tags will not be available for customers to add to their subscriptions.",
        fieldValue: "",
      },
      {
        key: "specificZipPostalCodesAllowedForDelivery",
        fieldType: "text input",
        fieldLabel: "Specific zip/postal codes allowed for delivery",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "",
        disable: true,
      },
      {
        key: "zipPostalCodesAllowedForLocalDelivery",
        fieldType: "text input",
        fieldLabel: "Zip/postal codes allowed for local delivery",
        fieldDescription: "Upgrade your plan to enable this feature.",
        fieldValue: "",
        disable: true,
      },
    ],
  },
  {
    title: "Product Filter Menu Settings",
    fields: [
      {
        key: "createProductFilter",
        fieldType: "checkbox",
        fieldLabel: "Create Product Filter",
        fieldValue: "false",
      },
      {
        key: "filterGroupType",
        fieldType: "options - dropdown",
        fieldLabel: "Filter Group Type",
        fieldValue: "Select Filter",
        fieldOptions: "Select Filter, Vendor, Product Type, Tags, Sorting, Title Or Variants",
      },
    ],
  },
];